baseURL = "https://www.corwinkcosmetics.com/"
languageCode = "en-us"
title = "Corwink Cosmetics"
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 6
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 5
[[menu.main]]
name = "Shop"
url = "/products"
weight = 2
[[menu.main]]
name = "Feedback"
url = "/feedback"
weight = 3
[[menu.main]]
name = "FAQ"
url = "/faq"
weight = 4
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[taxonomies]
category = "categories"
eyeliner = "eyeliners"
lash-material = "lash-materials"
lash-type = "lash-types"
tag = "tags"
collection = "collections"
